name: 'Code Style: Black'

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - "!**/*.md/**"
env:
  CI: true
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Black 
        run: |
          pip install git+git://github.com/psf/black
        id: pip
 
      - name: Run Lint 
        run: |
          black .
        id: black
